easy_admin:
    entities:
        Utilisateur:
            controller: App\Controller\Admin\UtilisateurCrudController
        Login:
            controller: App\Controller\Admin\LoginCrudController
        Profil:
            controller: App\Controller\Admin\ProfilCrudController
        DossierPatient:
            controller: App\Controller\Admin\DossierPatientCrudController
        Greffe:
            controller: App\Controller\Admin\GreffeCrudController
