twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates/admin': admin
        '%kernel.project_dir%/templates/medecin': medecin

when@test:
    twig:
        strict_variables: true
